---
#Install all Services needed to setup Microsoft Active Directory Services
- name: Install AD Services
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes
    state: present
  register: result



#Set up AD Domain 
- name: Configure AD Services
  win_domain:
    dns_domain_name: "{{domain_name}}"
    safe_mode_password: "{{ ad_recovery_password }}"
  register: ad
  

#Reboot System
- name: reboot server
  win_reboot:
    msg: "Installing AD. Rebooting..."
    pre_reboot_delay: 15
    post_reboot_delay: 300
  when: ad.changed


#Wait for System to come up
- name: Wait on connect
  wait_for_connection:
    delay: 60
    timeout: 1800

- name: Gather facts for the first time
  setup:

#Create and fill the Central Group Policy Store
- name: Copy PolicyDefinitions Folder
  win_copy:
    src: C:\Windows\PolicyDefinitions\
    dest: C:\Windows\SYSVOL\sysvol\{{ domain_name }}\Policies\PolicyDefinitions\
    remote_src: yes
